### PR TITLE
Fix truncation error precision adjustments

### PR DESCRIPTION
**Pull request by dmcdougall**
We adjust the truncation error precision, not the emulator precision.
We also fix the adjustment to the scale parameter of the Gamma
distribution.  The adjustment in the paper is additive on the rate, not the
scale.

This commit also also updates the functional regression test solutions.

### CODE REVIEW

**Comment by roystgnr** [comment]
This didn't change any of the multivariate regression solutions?

**Review by roystgnr — APPROVED** [review]
Good catches, on all of that.

**Comment by dmcdougall** [comment]
> This didn't change any of the multivariate regression solutions?

You mean the multivariate regression solutions we won't have until we merge #654?  Nope.

:)

**Comment by dmcdougall** [comment]
Oh I'm an idiot.

No, it didn't change the multivariate regressions.  That's surprising...

**Comment by roystgnr** [comment]
Surprising but I suppose not inconceivable?  In Brian's email at least one of the corresponding changes only had an effect several decimal places out...

**Pull request merged**
