### PR TITLE
Fix "make check" for out-of-source builds

### PR DESCRIPTION
**Pull request by roystgnr**

### CODE REVIEW

**Comment by pbauman** [comment]
Thanks. We should update the Travis file to use out-of-source builds for testing.

**Comment by dmcdougall** [comment]
Tests pass out of source for me locally.

**Comment by dmcdougall** [comment]
@roystgnr Can you `cherry-pick` a48a287 to `v0.55.0-release`, please?

**Comment by roystgnr** [comment]
Got it.

**Comment by dmcdougall** [comment]
Thanks.

**Pull request merged**
