### PR TITLE
Updated the doxygen docs to be for 0.57.1

### PR DESCRIPTION
**Pull request by teresaportone**
Added a sidebar and search bar.

### CODE REVIEW

**Comment by dmcdougall** [comment]
Huh, you shouldn't need commit 5276263 because of [this line](https://github.com/libqueso/queso/blob/dev/doxygen/queso.page#L3).

Aside from that, this looks good to me.

**Review by dmcdougall — APPROVED** [review]

**Comment by teresaportone** [comment]
The environmental variable for the version wasn't set for the first time around.

**Comment by dmcdougall** [comment]
Yeah that's what I figured.  Thanks for doing that.

**Comment by dmcdougall** [comment]
Now it's up on the website: http://libqueso.com/queso/html/

Thanks again.

**Pull request merged**
