### PR TITLE
Fix an indexing in error in BT_Wy_B ridge addition

### PR DESCRIPTION
**Pull request by dmcdougall**
We were indexing over the number of rows of B, but this is wrong.  The
number of rows it has is the number of columns of B.

### CODE REVIEW

**Comment by roystgnr** [comment]
Did we have Brows==Bcols before?  I don't see how this bug caused neither solution changes nor segfaults otherwise.

**Comment by dmcdougall** [comment]
I guess we must have.

**Comment by roystgnr** [comment]
Could we throw two asserts in there, demanding that BT_Wy_B_inv has the same number of rows and cols and that they're both Bcols?

**Comment by roystgnr** [comment]
I know, closing the barn door after the horses have left, but we might refactor at some point.

**Comment by dmcdougall** [comment]
Done.

**Review by roystgnr — APPROVED** [review]
Looks good, ready to merge when Travis is.

**Pull request merged**
