### PR TITLE
Deprecate `FiniteDistribution` and `DiscreteSubset`

### PR DESCRIPTION
**Pull request by dmcdougall**
Addresses first stage of #341.

### CODE REVIEW

**Comment by dmcdougall** [comment]
Anybody fancy doing a quick review of this?

**Comment by pbauman** [comment]
Was this functional? If not, then :+1: If so, do you think it's worth keeping?

**Comment by dmcdougall** [comment]
> Was this functional?

I have no idea; we have no tests for it.

> If so, do you think it's worth keeping?

Supporting discrete random variables?  No.  The transition kernel looks totally different.

**Comment by dmcdougall** [comment]
@pbauman Thanks for the review.  I'm going to merge this.  If anybody has any objections we can revert the commit, otherwise I think these classes should eat it.

**Pull request merged**
