### PR TITLE
Add test for BaseVectorSequence::unifiedPositionsOfMaximum

### PR DESCRIPTION
**Pull request by dmcdougall**

### CODE REVIEW

**Comment by dmcdougall** [comment]
This should now fix #308.  @beanSnippet can you confirm this?  And also that `make check` passes, too?

**Comment by dmcdougall** [comment]
I think #308 is serious enough to warrant a `v0.51.1` bugfix release.

@beanSnippet As soon as you let me know this fixes the problem, I can get that sorted out.

**Comment by beanSnippet** [comment]
Make check looks good. With my code however, sometimes it works on multiple
processors and sometimes it doesn't! Just changing the number of samples in
the chain can be the difference. So I'm not sure what's going on now...

**Comment by dmcdougall** [comment]
>Make check looks good. With my code however, sometimes it works on multiple
processors and sometimes it doesn't! Just changing the number of samples in
the chain can be the difference. So I'm not sure what's going on now...

With the same example code?  And are you getting the same error message?

**Comment by beanSnippet** [comment]
Yes, same example code and same error message. The only difference I've found so far is that it will work when the chain length is <5 (before it was always failing on multiple processors), but not for >= 5.

**Comment by beanSnippet** [comment]
Was a path problem on my end, the fix holds, thanks @dmcdougall (for the fix and path help).

**Comment by dmcdougall** [comment]
Happy to help.

I'll merge this into a bugfix branch first so I can roll up a bugfix release.  That way the DAKOTA folks don't get bitten.

**Comment by dmcdougall** [comment]
Replaced by #324.

**Pull request closed without merging**
