### PR TITLE
Adding OptimizerOptions

### PR DESCRIPTION
**Pull request by dmcdougall**
This is work in progress, but this should enable the user to tweak certain options for the optimiser from the queso input file.

### CODE REVIEW

**Comment by dmcdougall** [comment]
This is related to #300.

**Comment by dmcdougall** [comment]
Can't seem to trigger a TravisCI build with this branch.  Hmmm.  At least the tests are passing locally.

**Comment by dmcdougall** [comment]
Ok, I don't really see a reason not to merge this.  If anyone has any feedback they'd like to give I'd be more than happy to implement it.

**Comment by nicholasmalaya** [comment]
@dmcdougall I can look at this next week if you want a 2nd pair of eyes, otherwise I say go for the merge.

**Comment by dmcdougall** [comment]
Alright, merging.

**Pull request merged**
