### PR TITLE
Autoconf cleanup

### PR DESCRIPTION
**Pull request by roystgnr**
By checking $srcdir, we can have scripts and executables read their inputs from there rather than making copies with configure.

In the process, I added a FullEnvironment and superclass constructor overload to take std::string instead of char* arguments.

Let me know if anyone wants that constructor broken into a separate PR, or wants some of the commits in this PR turned into fixups; the final result here is pretty clean, but the history doesn't all pass make check.

### CODE REVIEW

**Comment by pbauman** [comment]
Looks good to me.

**Comment by dmcdougall** [comment]
`make distcheck` is failing for me:

```
$ make distcheck
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory `/scratch/damon/git/queso'
if test -d "queso-0.54.0"; then find "queso-0.54.0" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "queso-0.54.0" || { sleep 5 && rm -rf "queso-0.54.0"; }; else :; fi
test -d "queso-0.54.0" || mkdir "queso-0.54.0"
 (cd inc/queso && make  top_distdir=../../queso-0.54.0 distdir=../../queso-0.54.0/inc/queso \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/scratch/damon/git/queso/inc/queso'
make[2]: Leaving directory `/scratch/damon/git/queso/inc/queso'
 (cd src/contrib/ANN && make  top_distdir=../../../queso-0.54.0 distdir=../../../queso-0.54.0/src/contrib/ANN \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/scratch/damon/git/queso/src/contrib/ANN'
 (cd test && make  top_distdir=../../../../queso-0.54.0 distdir=../../../../queso-0.54.0/src/contrib/ANN/test \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/scratch/damon/git/queso/src/contrib/ANN/test'
make[3]: Leaving directory `/scratch/damon/git/queso/src/contrib/ANN/test'
make[2]: Leaving directory `/scratch/damon/git/queso/src/contrib/ANN'
 (cd src && make  top_distdir=../queso-0.54.0 distdir=../queso-0.54.0/src \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/scratch/damon/git/queso/src'
make[2]: Leaving directory `/scratch/damon/git/queso/src'
 (cd examples && make  top_distdir=../queso-0.54.0 distdir=../queso-0.54.0/examples \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/scratch/damon/git/queso/examples'
make[2]: Leaving directory `/scratch/damon/git/queso/examples'
 (cd test/gsl_tests && make  top_distdir=../../queso-0.54.0 distdir=../../queso-0.54.0/test/gsl_tests \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/scratch/damon/git/queso/test/gsl_tests'
make[2]: Leaving directory `/scratch/damon/git/queso/test/gsl_tests'
 (cd test && make  top_distdir=../queso-0.54.0 distdir=../queso-0.54.0/test \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/scratch/damon/git/queso/test'
make[2]: *** No rule to make target `test_Regression/GaussianMean1DRegression_options.in', needed by `distdir'.  Stop.
make[2]: Leaving directory `/scratch/damon/git/queso/test'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/scratch/damon/git/queso'
make: *** [dist] Error 2
```

**Comment by roystgnr** [comment]
Jerk!  It didn't pass distcheck *before* this PR either; you're missing the headers in the newest test in the appropriate _SOURCES.

I'll put the fix for that in a separate PR so it's easier to cherry-pick into the release branch too.

**Comment by dmcdougall** [comment]
Gah, sorry about that.  I'll open a PR to have Travis run `make distcheck`.

**Pull request merged**
