### PR TITLE
Make boost program options optional

### PR DESCRIPTION
**Pull request by dmcdougall**
`configure --disable-boost-program-options`.

This is initial work, and the history certainly needs to be cleaned up before merging.  I'm opening this PR because I finally got the tests passing.

### CODE REVIEW

**Comment by dmcdougall** [comment]
Ok, I think I'm happy with this now.  Feedback welcome.

**Comment by pbauman** [comment]
OK, so the strategy is you first have to opt-in to opt-out of Boost PO and then, later, we'll make opting out default?

**Comment by dmcdougall** [comment]
Yeah, boost program options is enabled by default.  Passing in `--disable-boost-program-options` disables it and uses GetPot instead.

With #430 merged, I wonder if we should actually just use `--without-boost` instead, though.

**Comment by dmcdougall** [comment]
I messed up something, apparently.

**Comment by dmcdougall** [comment]
Oh yeah, ok, I removed headers instead of `#ifdef`ing around them.  Duh.

**Comment by dmcdougall** [comment]
Ok we're good.

**Comment by dmcdougall** [comment]
@pbauman Any comments before I merge this sucker?

**Pull request merged**
