### PR TITLE
GCC 4.4.7 compatibility: typename, template bracket

### PR DESCRIPTION
**Pull request by briadam**
Minimum queso-0.56.0 changes needed for gcc-4.4.7
* Fix template `<T>>` to `<T> >`
 * A number of SharedPtr had typename prefix in non-templated classes

Of the remaining instances of `typename SharedPtr|ScopedPtr`, I believe the following files also need review, but I'm not building these files for Dakota, so can't edit/test.
```
src/core/src/InfiniteDimensionalMCMCSampler.C
src/core/src/LibMeshOperatorBase.C
src/core/src/LibMeshFunction.C
src/core/src/LibMeshNegativeLaplacianOperator.C
src/core/inc/InfiniteDimensionalMCMCSampler.h
src/core/inc/LibMeshFunction.h
src/core/inc/LibMeshOperatorBase.h
```

These uses appear fine (don't need review) as they are in templated classes
```
src/core/inc/Factory.h
src/gp/inc/GPMSA.h
src/stats/inc/MetropolisHastingsSG.h
src/surrogates/inc/InterpolationSurrogateIOBase.h
```

### CODE REVIEW

**Comment by dmcdougall** [comment]
This targets `dev`.  I'll create a hotfix branch for you so you can have a bugfix release.

**Comment by dmcdougall** [comment]
@briadam Cool, thanks.  It's merged in `hotfix-0.56.1` (see commit b1d0366).

If you have more fixes, target the hotfix branch, otherwise look out for a v0.56.1.

**Comment by briadam** [comment]
@dmcdougall  I see.  I had checked out a branch based on v0.56.0-release, but I guess when I create the pull request I have to select the branch that it targets.  Thanks for merging to the hotfix branch.

Should I open an Issue for the remaining LibMesh / InfiniteDimenional issues that need review?

**Comment by dmcdougall** [comment]
> but I guess when I create the pull request I have to select the branch that it targets

Yes, that's exactly right.  It's really easy to miss it, too:

screenshot at 2016-12-01 09-57-25
.

**Comment by dmcdougall** [comment]
> Should I open an Issue for the remaining LibMesh / InfiniteDimenional issues that need review?

Ah, I missed the fact they weren't here.  Yes, open an issue so I don't forget.  I guess you're not in a rush for that patch since Dakota doesn't use this functionality, correct?

**Comment by briadam** [comment]
None of these patches are time critical as we're already made them on our local git repos.  As long as they get integrated into next minor release, life is good.  I created #489 for the LibMesh and InfiniteDimensional files so we don't lose track.

**Comment by dmcdougall** [comment]
@briadam Cheers!

**Pull request closed without merging**
