### PR TITLE
Fix uqGslVector test seg fault

### PR DESCRIPTION
**Pull request by briadam**
Proposed fix for #405

### CODE REVIEW

**Comment by pbauman** [comment]
Was the problem just that the env was being deleted before the parameter space was destroyed? Smaller fix would just be to scope the parameter space, right? Regardless, thanks for reporting and taking a crack at the fix.

**Comment by briadam** [comment]
Yes, you are correct.  I first fixed it that way (adding braces) for big_param_space, but then realized that param_space was constructed via new and would have to be deleted anyway (or similarly scope-limited), so just decided to follow the existing memory management pattern rather than have two.

**Comment by dmcdougall** [comment]
I wrote this test before I knew about safer memory manage patterns and smart pointers.  I'm ok with this fix, although in future I think passing references or `SharedPtr`s around would be preferable.

**Comment by pbauman** [comment]
:+1:

**Comment by dmcdougall** [comment]
@briadam Thanks!

**Pull request merged**
