### PR TITLE
Use boost::math::isnan, don't rely on C99/C++11

### PR DESCRIPTION
**Pull request by roystgnr**
Hopefully this will fix the problem @dmcdougall hit on OSX.

### CODE REVIEW

**Comment by pbauman** [comment]
Would be nice to use the solution in #430

**Comment by pbauman** [comment]
Which is not yet merged, I should say.

**Comment by roystgnr** [comment]
Shit.  I should try to keep up.

**Comment by roystgnr** [comment]
The goal is for boost to be an optional dependency whenever we have C++11?  In that case #430 is definitely the better solution.

**Comment by dmcdougall** [comment]
Let's use this as an intermediate patch before #430.

**Comment by dmcdougall** [comment]
Thanks @roystgnr.

**Pull request merged**
