### PR TITLE
Add SharedPtr

### PR DESCRIPTION
**Pull request by dmcdougall**
In a similar vein to #368, this adds a `SharedPtr` type.

### CODE REVIEW

**Comment by pbauman** [comment]
:+1:

**Comment by roystgnr** [comment]
Well, it adds a SharedPtr<T>::Type type, anyway.  Damn C++03.

:+1:

**Comment by roystgnr** [comment]
Silly thought: could/should we use inheritance here, rather than the nested type trick, so we don't have to write ::Type everywhere?

**Comment by pbauman** [comment]
I defer to @roystgnr's sensibilities here.

**Pull request merged**
