### PR TITLE
Fixes for Gauss-Hermite Quadrature, Actually Test Gauss-Hermite Quadrature

### PR DESCRIPTION
**Pull request by pbauman**
In the process of adding unit tests for the Gauss-Hermite quadrature, I found two errors there (fb187e0 ac2eab6). Those errors are fixed and we have testing for Gauss-Hermite now.

### CODE REVIEW

**Comment by dmcdougall** [comment]
```
misc/src/1DQuadrature.C:604:25: error: aggregate ‘std::stringstream ss’ has incomplete type and cannot be defined
```

**Comment by pbauman** [comment]
*sigh* pushed a fix. Should I squash it into fb187e0?

**Comment by pbauman** [comment]
OK, I went ahead and squashed it in.

**Comment by pbauman** [comment]
OK, so I'm inferring that the codecov/patch failure is it doesn't like that only 50% of the diff ends up being tested?

That's because the other 50% is an error message. As far as I'm concerned, this is good to merge, but will wait for @dmcdougall.

**Comment by dmcdougall** [comment]
Yup.

**Pull request merged**
