### PR TITLE
Make copy ctor for DistArray and VectorSpace private

### LINKED ISSUE #57: Test VectorSpace copy constructor
This relies on the `copy` method in `DistArray` being implemented.

### PR DESCRIPTION
**Pull request by dmcdougall**
They were throwing exceptions at run-time anyway, so clearly nobody was using them.

This addresses a comment made by @pbauman in #55, and fixes #57.

### CODE REVIEW

**Comment by pbauman** [comment]
Fine with me. Can revisit if someone decides they need to copy the vector space.

**Comment by pbauman** [comment]
What is the purpose of `DistArray` BTW? Where is that used?

**Comment by dmcdougall** [comment]
> What is the purpose of DistArray BTW? Where is that used?

I have no idea.

**Comment by dmcdougall** [comment]
The failure was a decrease in coverage, which I expected.

**Pull request merged**
