### PR TITLE
Fix sign error in lnValue of JeffreysJointPdf

### PR DESCRIPTION
**Pull request by dmcdougall**
The Jeffreys prior is 1.0 / x.  Log of it is log(1.0 / x) = -x, but what was returned was the negative of this.

### CODE REVIEW

**Comment by dmcdougall** [comment]
> The Jeffreys prior is 1.0 / x. Log of it is log(1.0 / x) = -x, but what was returned was the negative of this.

Oops, I meant log(1.0 / x) = -log(x).

**Comment by beanSnippet** [comment]
I am confused-- I thought the pdf was supposed to transform a sample from a uniform distribution (domainVector[i]) to another distribution, not evaluate the pdf at that point...?

**Comment by dmcdougall** [comment]
Are you referring to [Inverse Transform Sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling)?  `actualValue` at a point should certainly return the pdf of the random at that point.

**Comment by beanSnippet** [comment]
Oh, I think I was thinking of ```VectorRealizer```. Nevermind.

**Pull request merged**
