### PR TITLE
Fix github language statistics

### PR DESCRIPTION
**Pull request by dmcdougall**

### CODE REVIEW

**Comment by dmcdougall** [comment]
New stats:

```bash
$ linguist
84.38%  C++
8.78%   TeX
5.89%   Perl
0.33%   Makefile
0.27%   Shell
0.16%   Python
0.13%   FORTRAN
0.05%   C
0.00%   HTML
```

**Comment by nicholasmalaya** [comment]
This is cool, I had not seen this before. Will definitely steal for other projects.

**Comment by pbauman** [comment]
Nice.

**Comment by dmcdougall** [comment]
Someone push the button.

**Comment by nicholasmalaya** [comment]
FIRE TORPEDOS

**Pull request merged**
