### PR TITLE
Libmesh compatibility fixes

### PR DESCRIPTION
**Pull request by roystgnr**
This replaces #286, and includes both those fixes plus fixes for newer changes.

We now work fine with master again, all tests passing.  I'll see how far back compatibility goes and set a minimum version number before we merge.

### CODE REVIEW

**Comment by dmcdougall** [comment]
I'm happy with requiring at least `0.9.x` in `configure.ac`.  The rest of this looks fine.

**Comment by dmcdougall** [comment]
@roystgnr Can you please update [this line in `configure.ac`](https://github.com/libqueso/queso/blob/dev/configure.ac#L111) to require a newer libmesh?

**Comment by roystgnr** [comment]
This should be ready to merge now.  Sorry about the delays.

**Comment by dmcdougall** [comment]
No problem.  I'd like this in the next release but it looks like you branched from `dev`; do you mind if I cherry-pick your commits into a new branch off of `v0.52-release` instead?

**Comment by roystgnr** [comment]
I'd assume you'd want to cherry-pick-to-0.52 *in addition* to merging-to-dev; why do you say *instead*?

**Comment by dmcdougall** [comment]
>I'd assume you'd want to cherry-pick-to-0.52 in addition to merging-to-dev; why do you say instead?

You're right.  I'll be merging 0.52 into dev regardless.

**Comment by dmcdougall** [comment]
Merged.

**Pull request closed without merging**
